corrected code of intendation in yaml

diff --git a/.github/workflows/01-build-blocks.yaml b/.github/workflows/01-build-blocks.yaml
--- a/.github/workflows/01-build-blocks.yaml
+++ b/.github/workflows/01-build-blocks.yaml
@@ -1,16 +1,18 @@
+
 name: 01 - Building Blocks
 on: push
 jobs:
- name: echo-hello
- runs-on: ubuntu-latest
- steps:
-  - name: Say Hello
-    run: echo "Hello, World!"
- name: echo-goodbye
- runs-on: ubuntu-latest
- steps:
-  - name: failed step
-    run: echo "failed"
-         exit 1
-  - name: say goodbye
-    run: echo "Goodbye, World!"
+  echo-hello:
+    runs-on: ubuntu-latest
+    steps:
+      - name: Say Hello
+        run: echo "Hello, World!"
+  echo-goodbye:
+    runs-on: ubuntu-latest
+    steps:
+      - name: failed step
+        run: |
+          echo "failed"
+          exit 1
+      - name: say goodbye
+        run: echo "Goodbye, World!"
